version: "3.9"
services:
  
  db:
    image: postgres:14.5
    restart: unless-stopped
    volumes:
      - postgres_db:/var/lib/postgresql/data/
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}


  # blog_service:
  #   container_name: django   
  #   build:
  #     context: ../../src
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8000:8000" 
  #   restart: always
  #   volumes:
  #     - static_value:/app/static/
  #     - media_value:/app/media/
  #   depends_on:
  #     - db
  #     - redis
  #   env_file:
  #     - ./.env


  redis:
    container_name: redis   
    image: redis:latest
    restart: unless-stopped
    ports:
      - "6379"

volumes:
  # static_value:
  # media_value:
  postgres_db:







